# Generated by Django 3.2.9 on 2021-11-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capBackend', '0003_auto_20211121_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(default='no description', max_length=500),
        ),
    ]
